apiVersion: v1
kind: Namespace
metadata:
  name: wiz-lab
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wizexercise
  namespace: wiz-lab
data:
  wizexercise.txt: |
    Robert Irwin
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wiz-lab-sa
  namespace: wiz-lab
---
# INTENTIONAL MISCONFIGURATION: cluster-admin privileges on app service account
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wiz-lab-crb
subjects:
- kind: ServiceAccount
  name: wiz-lab-sa
  namespace: wiz-lab
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiz-lab-app
  namespace: wiz-lab
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: wiz-lab-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wiz-lab-app
    spec:
      serviceAccountName: wiz-lab-sa
      containers:
      - name: wiz-lab-app
        image: 180294223177.dkr.ecr.us-east-1.amazonaws.com/wiz-lab-app:latest
        # INTENTIONAL MISCONFIGURATION: plaintext MongoDB URI as environment variable
        env:
        - name: MONGO_URI
          value: "mongodb://admin:password123@10.0.15.11:27017/appdb"
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: wizexercise
          mountPath: /usr/share/nginx/html/wizexercise.txt
          subPath: wizexercise.txt
      volumes:
      - name: wizexercise
        configMap:
          name: wizexercise
---
apiVersion: v1
kind: Service
metadata:
  name: wiz-lab-svc
  namespace: wiz-lab
spec:
  selector:
    app.kubernetes.io/name: wiz-lab-app
  ports:
  - port: 80
    targetPort: 5000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wiz-lab-ingress
  namespace: wiz-lab
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wiz-lab-svc
            port:
              number: 80
